 ```bash                                                                                                                                                                                                                                                                        
   cd rustdesk-1.4.1                                                                                                                                                                                                                                                            
   cat > push.sh << 'EOF'                                                                                                                                                                                                                                                       
   #!/bin/bash                                                                                                                                                                                                                                                                  
   read -p "GitHub用户名: " u                                                                                                                                                                                                                                                   
   read -p "仓库名: " r                                                                                                                                                                                                                                                         
   git init && git add . && git commit -m "init"                                                                                                                                                                                                                                
   git remote add origin https://github.com/$u/$r.git                                                                                                                                                                                                                           
   git push -u origin main                                                                                                                                                                                                                                                      
   EOF                                                                                                                                                                                                                                                                          
   chmod +x push.sh && ./push.sh                                                                                                                                                                                                                                                
 ``` 